easy_admin:

    formats:
      date:     'd/m/Y'
      time:     'H:i'
      datetime: 'd/m/Y H:i:s'

    design:
      brand_color: '#1ABC9C'
      menu:
        - label: 'Home'
          icon: 'images'

        - label: 'Galerie'
          icon: 'images'
          children:
            - { entity: 'Image', icon : 'images'}
            - {entity: 'AccueilImage', icon : 'image'}
            - {entity: 'BackgroundImage',icon : 'image'}
            - {entity: 'ArticleImages',icon: 'image'}

        -  label: 'Articles'
           icon : 'newspaper-o'
           children:
              - { entity: 'Article', icon : 'newspaper-o'}
              - { entity: 'Category', icon : 'tag'}

        -  label: 'Utilisateurs'
           icon :  'address-book'
           children:
             - { entity: 'User', icon : 'users' }

        -  label: 'Demandes de devis'
           icon : 'envelope-square'
           children:
              - { entity: 'RequestProject', icon : 'envelope-open-text'}


        -  label: 'Carrières'
           icon : 'briefcase'
           children:
              - { entity: 'Offer', icon : 'business-time'}
              - { entity: 'OfferType', icon : 'tag'}

              - { entity: 'Application', icon : 'business-time'}







    user:
      display_name: true
      display_avatar: true
      name_property_path: 'username'
      avatar_property_path: 'gravatar'


    site_name: 'ABC Legermain'
    entities:
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Editer les articles'}
                - title
                - {property: 'content', type: 'text-editor'}
                - {type: 'group', icon: 'pencil', label: 'Autres informations'}
                - category
                -  {type: 'group', icon: 'pencil', label: 'Option automatique'}
                - articleImages
            list:
              collapse_actions: true
              actions: ['show', 'edit', 'delete']
              filters: ['category','createdAt']
              batch_actions: ['delete']

            show:
              fields:
                - id
                -  title
                -  { property: 'content', type: 'raw'}
                -  createdAt
                -  category
                -  articleImages



        Category:
            class : App\Entity\Category
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Editer les catégories'}
                - title
                - {property: 'content', type: 'text-editor'}
                - {type: 'group', icon: 'pencil', label: 'Options automatiques'}
                - requestProjects
                - articles
                - backgroundImages
            list:
              collapse_actions: true
              actions: ['show', 'edit', 'delete']
              batch_actions: ['delete']
            show:
              fields:
                - id
                - title
                - {property: 'content', type: 'raw'}
                - requestProjects
                - articles
                - backgroundImages


        Image:
            class:  App\Entity\Image
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Editer les images'}
                - { property : 'imageFile', type: 'vich_image'}
            list:
              collapse_actions: true
              actions: ['show', 'edit', 'delete']
              batch_actions: ['delete']


        User:
            class : App\Entity\User
            label : 'Utilisateurs'
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Client', css_class: 'col-lg-6'}
                - name
                - firstname
                - {type: 'group', icon: 'pencil', label: 'Contacts', css_class: 'col-lg-6'}
                - email
                - number
                - {type: 'group', icon: 'pencil', label: 'Adresse', css_class: 'col-lg-6 '}
                - address
                - {type: 'group', icon: 'pencil', label: 'Autres informations', css_class: 'col-lg-6'}
                - applications
                - requestProjects
            list:
              collapse_actions: true
              actions: ['show', 'edit', 'delete']
              batch_actions: ['delete']



        Application:
           class: App\Entity\Application
           label: 'Candidature'
           form:
             fields:
              - {type: 'group', icon: 'pencil', label: 'Candidature'}
              - { property : 'cvFile', type: 'vich_file' }
              - { property : 'resumeFile', type: 'vich_file'}
              - { property : 'offer', type: 'easyadmin_autocomplete', type_options: { multiple: false }}
              - { property : 'user', type: 'easyadmin_autocomplete', type_options: { multiple: false }}
           list:
             collapse_actions: true
             actions: ['show', 'edit', 'delete']
             batch_actions: ['delete']

        OfferType:
           class: App\Entity\OfferType
           label: "Type de l'offre"
           form:
             fields:
               - {type: 'group', icon: 'pencil', label: 'Type de contrat'}
               - title
               - offers
           list:
             collapse_actions: true
             actions: ['show', 'edit', 'delete']
             batch_actions: ['delete']

        Offer:
           class: App\Entity\Offer
           label: 'Offre'
           form:
             fields:
               - {type: 'group', icon: 'pencil', label: 'Offre de travail'}
               - { property: 'title'}
               - { property: 'hourlyWage'}
               - { property: 'address'}
               - { property: 'content', type: 'text-editor'}
               - {type: 'group', icon: 'pencil', label: 'Durée du contrat', css_class: 'col-lg-6'}
               - { property: 'beginAt'}
               - { property: 'endAt'}
               - {type: 'group', icon: 'pencil', label: 'Autres informations', css_class: 'col-lg-6'}
               - { property: 'offerType', type: 'easyadmin_autocomplete', type_options: { multiple: false }}
           list:
               fields:
                 - id
                 - title
                 - accepted
                 - hourlyWage
                 - createdAt
                 - address
                 - offerType

               collapse_actions: true
               actions: ['show', 'edit', 'delete']
               batch_actions: ['delete']
           show:
               fields:
                 - title
                 - { property: 'content', type: 'raw'}
                 - beginAt
                 - endAt
                 - createdAt
                 - hourlyWag
                 - address
                 - { property: 'offerType', type: 'easyadmin_autocomplete', type_options: { multiple: false }}







        RequestProject:
           class: App\Entity\RequestProject
           label: 'Demande de devis'
           form:
             fields:
               - {type: 'group', icon: 'pencil', label: 'Demande de devis', css_class: 'col-lg-6'}
               - { property : 'title'}
               - { property : 'content'}
               - {type: 'group', icon: 'pencil', label: 'Autres informations', css_class: 'col-lg-6'}
               - { property : 'user', type: 'easyadmin_autocomplete', type_options: { multiple: false }}
               - { property: 'category', type: 'easyadmin_autocomplete', type_options: { multiple: false } }

           list:
              collapse_actions: true
              actions: ['show', 'edit', 'delete']
              batch_actions: ['delete']


        AccueilImage:
          class: App\Entity\AccueilImage
          form:
            fields:
              - {type: 'group', icon: 'pencil', label: 'Image de la page d accueil'}
              - image
          list:
            collapse_actions: true
            actions: ['show', 'edit', 'delete']
            batch_actions: ['delete']


        BackgroundImage:
          class: App\Entity\BackgroundImage
          form:
            fields:
              - {type: 'group', icon: 'pencil', label: 'Image en arrière plan'}
              - image
              - category
          list:
            collapse_actions: true
            actions: ['show', 'edit', 'delete']
            batch_actions: ['delete']

        ArticleImages:
          class: App\Entity\ArticleImages
          form:
            fields:
              - {type: 'group', icon: 'pencil', label: 'Images des pages d articles'}
              - article
              - image
          list:
            collapse_actions: true
            actions: ['show', 'edit', 'delete']
            batch_actions: ['delete']
