easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Article
        - App\Entity\Category
        - App\Entity\Image
        - App\Entity\User
        - App\Entity\Applicant
        - App\Entity\Application
        - App\Entity\Offer
        - App\Entity\OfferType
        - App\Entity\Customer
        - App\Entity\RequestProject
