easy_admin:

    formats:
      date:     'd/m/Y'
      time:     'H:i'
      datetime: 'd/m/Y H:i:s'

    design:
      form_theme:
        - '@EasyAdmin/form/bootstrap_4.html.twig'




      brand_color: '#1ABC9C'
      menu:
        - label: 'Home'
          icon: 'images'

        - label: 'Galerie'
          icon: 'images'
          children:
            - { entity: 'Image', icon : 'images'}

            - {entity: 'Articles_Images', icon : 'image'}
            - {entity: 'Articles_Accueil_Images',icon : 'image'}


        -  label: 'Articles'
           icon : 'newspaper-o'
           children:
              - { entity: 'Articles', icon : 'newspaper-o'}
              - { entity: 'Catégories', icon : 'tag'}

        -  label: 'Utilisateurs'
           icon :  'address-book'
           children:
             - { entity: 'Utilisateurs', icon : 'users' }

        -  label: 'Demandes de devis'
           icon : 'envelope-square'
           children:
              - { entity: 'Devis', icon : 'envelope-open-text'}


        -  label: 'Carrières'
           icon : 'briefcase'
           children:
              - { entity: "Recrutements", icon : 'business-time'}
              - { entity: 'Contrats', icon : 'tag'}

              - { entity: 'Candidatures', icon : 'business-time'}

        - label: 'Actualités'
          icon: 'newspaper'
          children:
            - { entity: 'Actualities', icon : 'newspaper'}







    user:
      display_name: true
      display_avatar: true
      name_property_path: 'username'
      avatar_property_path: 'gravatar'


    site_name: 'ABC Legermain'
    entities:
        # List the entity class name you want to manage
        Articles:
            class: App\Entity\Article
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Editer les articles'}
                - {property: 'title', label : 'Titre'}
                - {property: 'content', type: 'text-editor', label: 'Contenu'}
                - {type: 'group', icon: 'pencil', label: 'Autres informations'}
                - {property: 'category', label : 'Catégorie'}
                -  {type: 'group', icon: 'pencil', label: 'Option automatique'}
                - {property: 'articleImages', label: 'Images'}
            list:
              fields:
                - id
                - { property: 'title', label: 'Titre'}
                - { property: 'createdAt', label: 'Publié le'}
                - { property: 'category', label: 'Catégorie'}
                - { property: 'articleImages', label: 'Images'}

              collapse_actions: true
              actions:
                - { name: 'edit', icon: 'pencil', css_class: 'btn btn-primary' }
                - { name: 'show', icon: 'eye', css_class: 'btn btn-secondary' }
                - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
              filters: ['category','createdAt']
              batch_actions: ['delete']

            show:
              fields:
                - id
                -  {property: 'title', label: 'Titre'}
                -  { property: 'content', type: 'raw', label: 'Contenu'}
                -  {property: 'createdAt', label: 'Publié le'}
                -  {property: 'category', label: 'Catégorie'}
                -  {property: 'articleImages', label: 'Images'}




        Catégories:
            class : App\Entity\Category
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Editer les catégories'}
                - {property: 'title', label: 'Titre'}
                - {property: 'content', type: 'text-editor', label: 'contenu'}
                - {type: 'group', icon: 'pencil', label: 'Options automatiques'}
                - {property: 'requestProjects', label: 'Devis'}
                - {property: 'articles', label: 'Articles'}
                - {property: 'backgroundImages', label: 'Images de fond'}

            list:
              fields:
                - {property: 'id'}
                - {property: 'title', label : 'Titre'}
                - {property: 'requestProjects', label : 'Devis'}
                - {property: 'articles', label : 'Articles'}
                - {property: 'backgroundImages', label : 'Images de fond'}
              collapse_actions: true
              actions:
                - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
                - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
                - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
              batch_actions: ['delete']
            show:
              fields:
                - {property: 'id'}
                - {property: 'title', label: 'Titre'}
                - {property: 'content', type: 'raw', label: 'Contenu'}
                - {property: 'requestProjects',  label: 'Devis'}
                - {property: 'articles',  label: 'Articles'}
                - {property: 'backgroundImages', type: 'raw', label: 'Images de fond'}



        Image:
            class:  App\Entity\Image
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Editer les images'}
                - { property : 'imageFile', type: 'vich_image'}
                - {property: 'accueil', label: 'Accueil'}
            list:
              fields:
                - id
                - {property: 'link', label: 'Lien'}
                - {property: 'accueil', label: 'Accueil'}
                - {property: 'actualities', label: 'Actualité'}
                - {property: 'articleImages', label: 'Image'}



              collapse_actions: true
              actions:
                - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
                - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
                - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
              batch_actions: ['delete']


        Utilisateurs:
            class : App\Entity\User
            label : 'Utilisateurs'
            disabled_actions: ['new']
            form:
              fields:
                - {type: 'group', icon: 'pencil', label: 'Client', css_class: 'col-lg-6'}
                - { property: 'firstname', label: 'Nom'}
                - {property: 'name', label: 'Prenom'}
                - {type: 'group', icon: 'pencil', label: 'Contacts', css_class: 'col-lg-6'}
                - { property: 'email',type: 'email' ,label: 'Email'}
                - { property: 'number', type: 'tel', label: 'Numéro'}
                - {type: 'group', icon: 'pencil', label: 'Adresse', css_class: 'col-lg-6 '}
                - {property: 'address',  label: 'Adresse'}
                - {type: 'group', icon: 'pencil', label: 'Autres informations', css_class: 'col-lg-6'}
                - {property: 'applications',  label: 'Candidatures'}
                - {property: 'requestProjects',  label: 'Devis'}
            show:
              - { property: 'firstname', label: 'Nom'}
              - { property: 'name', label: 'Prénom'}
              - { property: 'email',type: 'email' ,label: 'Email'}
              - { property: 'number', type: 'tel', label: 'Numéro'}
              - {property: 'address',  label: 'Adresse'}
              - {property: 'applications',  label: 'Candidatures'}
              - {property: 'requestProjects',  label: 'Devis'}

            list:
              fields:
                - { property: 'firstname', label: 'Nom'}
                - { property: 'name', label: 'Prénom'}
                - { property: 'email',type: 'email' ,label: 'Email'}
                - { property: 'number', type: 'tel', label: 'Numéro'}
                - {property: 'address',  label: 'Adresse'}
                - {property: 'applications',  label: 'Candidatures'}
                - {property: 'requestProjects',  label: 'Devis'}

              collapse_actions: true
              actions:
                - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
                - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
                - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }

              batch_actions: ['delete']




        Candidatures:
           class: App\Entity\Application
           label: 'Candidature'
           disabled_actions: ['new']
           form:
             fields:
              - {type: 'group', icon: 'pencil', label: 'Candidature'}
              - { property : 'cvFile', type: 'vich_file', label: 'CV' }
              - { property : 'resumeFile', type: 'vich_file', label: 'Lettre de motivation'}
              - { property : 'offer', type: 'easyadmin_autocomplete', type_options: { multiple: false }, label: 'Offre'}
              - { property : 'user', type: 'easyadmin_autocomplete', type_options: { multiple: false }, label: 'Postulant'}
           show:
             fields:
               - { property: 'cvFile', label: 'CV'}
               - { property: 'resumeFile', label: 'Lettre de motivation'}
               - { property: 'offer', label: 'Offre'}
               - { property: 'user', label: 'Postulant'}

           list:
             fields:
               - { property: 'cvFile', label: 'CV'}
               - { property: 'resumeFile', label: 'Lettre de motivation'}
               - { property: 'offer', label: 'Offre'}
               - { property: 'user', label: 'Postulant'}
             collapse_actions: true
             filters: ['offer','user']
             actions:
               - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
               - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
               - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
             batch_actions: ['delete']

        Contrats:
           class: App\Entity\OfferType
           label: "Type de l'offre"
           form:
             fields:
               - {type: 'group', icon: 'pencil', label: 'Type de contrat'}
               -  { property: 'title', label : 'Type de contrat'}
               - { property: 'offers', label : 'Offres'}
           show:
             fields:
               - id
               - { property: 'title', label: 'Type de contrat'}
               - { property: 'offers', label: 'Offres'}

           list:
             fields:
               - id
               - { property: 'title', label : 'Type de contrat'}
               - { property: 'offers', label : 'Offres'}
             collapse_actions: true
             actions:
               - { name: 'edit', icon: 'pencil', css_class: 'btn btn-primary' }
               - { name: 'show', icon: 'eye', css_class: 'btn btn-secondary' }
               - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
             batch_actions: ['delete']

        Recrutements:
           class: App\Entity\Offer
           label: 'Offre'
           form:
             fields:
               - {type: 'group', icon: 'pencil', label: 'Offre de travail'}
               - {property: 'title', label: 'Titre'}
               - {property: 'hourlyWage', label: 'honoraire'}
               - {property: 'address', label: 'adresse'}
               - { property: 'content', type: 'text-editor', label: 'Contenu'}
               - {type: 'group', icon: 'pencil', label: 'Durée du contrat', css_class: 'col-lg-6'}
               - { property: 'beginAt',label: 'Début du contrat'}
               - { property: 'endAt', label: 'Fin du contrat'}
               - {type: 'group', icon: 'pencil', label: 'Autres informations', css_class: 'col-lg-6'}
               - { property: 'offerType', type: 'easyadmin_autocomplete', type_options: { multiple: false }, label: 'Contrat'}

           list:
               fields:
                 - {property: 'id'}
                 - {property: 'title', label: 'Titre'}
                 - {property: 'accepted', label: 'Trouvé'}
                 - {property: 'hourlyWage', label: 'honoraire'}
                 - {property: 'createdAt', label: 'Publiée le'}
                 - {property: 'address', label: 'adresse'}
                 - {property: 'offerType', label: 'Contrat'}


               collapse_actions: true
               filters: ['offerType','accepted']
               actions:
                 - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
                 - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
                 - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
               batch_actions: ['delete']
           show:
             fields:
               - {property: 'id'}
               - {property: 'title', label: 'Titre'}
               - { property: 'content', type: 'raw', label: 'Contenu'}
               - {property: 'accepted', label: 'Trouvé'}
               - {property: 'hourlyWage', label: 'honoraire'}
               - {property: 'createdAt', label: 'Publiée le'}
               - {property: 'address', label: 'adresse'}
               - { property: 'offerType', label : 'Contrat'}







        Devis:
           class: App\Entity\RequestProject
           label: 'Demande de devis'

           form:
             fields:
               - {type: 'group', icon: 'pencil', label: 'Demande de devis', css_class: 'col-lg-6'}
               - { property : 'title', label: 'Titre'}
               - { property : 'content', label: 'Contenu'}
               - {type: 'group', icon: 'pencil', label: 'Autres informations', css_class: 'col-lg-6'}
               - { property : 'user', type: 'easyadmin_autocomplete', type_options: { multiple: false }, lable: 'Client'}
               - { property: 'category', type: 'easyadmin_autocomplete', type_options: { multiple: false },label: 'Catégorie' }
           show:
             fields:
               - id
               - { property: 'title', label: 'Titre'}
               - { property: 'content', label: 'Contenu'}
               - { property: 'user',  label: 'Client'}
               - { property: 'category', label: 'Catégorie' }
             actions:
                - { name: 'export', icon: 'file-export' , css_class: 'btn btn-primary', type: 'method'}


           list:
              fields:
               - id
               - { property: 'title', label: 'Titre'}
               - { property: 'createdAt', label: 'Envoyée le'}
               - { property: 'user',  label: 'Client'}
               - { property: 'category', label: 'Catégorie' }

              collapse_actions: true
              filters:
                - {property: 'category', label: 'Catégorie'}
                - {property: 'user', label: 'Client'}
                - {property: 'createdAt', label: 'Date'}
              actions:
                - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
                - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
                - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
                - { name: 'export', icon: 'file-export' , css_class: 'btn btn-primary', type: 'route'}
              batch_actions: ['delete']





        Articles_Accueil_Images:
          class: App\Entity\BackgroundImage
          form:
            fields:
              - {type: 'group', icon: 'pencil', label: 'Image en arrière plan'}
              - {property: 'image', label: 'Image'}
              - {property: 'category', label: 'Catégorie'}
          show:
            fields:
              - id
              - {property: 'image', label: 'Image'}
              - {property: 'category', label: 'Catégorie'}

          list:
            fields:
              - id
              - {property: 'image', label: 'Image'}
              - {property: 'category', label: 'Catégorie'}

            collapse_actions: true
            filters:
              - {property: 'category', label: 'Catégorie'}
            actions:
              - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
              - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
              - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }
            batch_actions: ['delete']

        Articles_Images:
          class: App\Entity\ArticleImages
          form:
            fields:
              - {type: 'group', icon: 'pencil', label: 'Images des pages d articles'}
              - {property: 'article', label: 'Article'}
              - {property: 'image', label: 'Image'}
          show:
            fields:
              - {property: 'article', label: 'Article'}
              - {property: 'image', label: 'Image'}

          list:
            fields:
              - {property: 'article', label: 'Article'}
              - {property: 'image', label: 'Image'}
            collapse_actions: true
            filters:
              - {property: 'article', label: 'Article'}
            actions:
              - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
              - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
              - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }

            batch_actions: ['delete']


        Actualities:
          class:  App\Entity\Actuality
          form:
            fields:
              - {type: 'group', icon: 'pencil', label: 'Actualités'}
              - {property: 'title', label: 'Titre'}
              - {property: 'content',type: 'text-editor', label: 'Contenu'}
              - {property: 'image', label: 'Image'}
          show:
            fields:
              - id
              - {property: 'title', label: 'Titre'}
              - {property: 'content', label: 'Contenu'}

          list:
            fields:
              - id
              - {property: 'title', label: 'Titre'}
              - {property: 'content', label: 'Contenu'}
            collapse_actions: true
            filters:
                  - { property: 'publishAt', label: 'Publié le'}
            actions:
              - { name: 'edit', icon: 'pencil', css_class: 'btn btn-secondary' }
              - { name: 'show', icon: 'eye', css_class: 'btn btn-primary' }
              - { name: 'delete', icon: 'trash', css_class: 'btn btn-danger' }

            batch_actions: ['delete']



