# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:

        thumb:
            quality: 75
            filters:
                thumbnail:
                    size:   [300, 300]
                    mode: outbound

        thumb2:
                    quality: 75
                    filters:
                        thumbnail:
                            size:   [238, 200]
                            mode: outbound

        thumb3:
                            quality: 75
                            filters:
                                thumbnail:
                                    size:   [200, 200]
                                    mode: outbound
        carousel:
                                    quality: 90
                                    filters:
                                        thumbnail:
                                            size:   [1300, 600]
                                            mode: outbound
        logo:
                                          quality: 90
                                          filters:
                                              thumbnail:
                                                  size:   [258, 100]
                                                  mode: outbound


